services:
  mongodb:
    image: mongo:8.0
    container_name: exposer-blog-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: exposer-db
    volumes:
      - mongodb_data:/data/db
#      - ./volumes/mongodb_data:/data/db  # best for local development
    networks:
      - exposer-blog-service

  redis:
    image: redis:8.4
    container_name: redis-exposer-caching
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    #      - ./volumes/redis_data:/data    # best for local development
    networks:
      - exposer-blog-service

  redis-insight:
    image: redis/redisinsight:3.0.2
    container_name: redis-insight
    ports:
      - "5540:5540"
    restart: always
    volumes:
      - redis-insight:/data
    #      - ./volumes/redis-insight:/data  # best for local development
    networks:
      - exposer-blog-service

volumes:
  mongodb_data:
  redis_data:
  redis-insight:

networks:
  exposer-blog-service:
    driver: bridge